// Generated by `npm run generate:contracts`; do not edit.
// Rust Serde/Schemars models are the declaration authority.

export type RustDaemonModels =
  | DockerSnapshot
  | GraphResponse
  | RuntimeMap
  | ComposeScan
  | ComposeGraph
  | ComposeEditPlan
  | LogsResponse
  | HealthResponse
  | ContainersResponse
  | ContainerRecord
  | ImagesResponse
  | NetworksResponse
  | VolumesResponse
  | FindingsResponse
  | ObservedChangeHistoryResponse;
export type ComposeMountKind = 'bind' | 'named_volume' | 'anonymous_volume' | 'unsupported';
export type RuntimeMode = 'docker' | 'mock';
export type RelationshipKind = 'connected_to' | 'mounts';
export type NodeKind = 'container' | 'network' | 'volume';
export type RuntimeProviderKind =
  | 'docker'
  | 'compose'
  | 'host'
  | 'systemd'
  | 'scheduled_job'
  | 'npm'
  | 'pm2'
  | 'tmux'
  | 'tailscale'
  | 'headscale'
  | 'cloudflare'
  | 'caddy'
  | 'reverse_proxy'
  | 'local_dns'
  | 'dns_provider'
  | 'external_api'
  | 'process'
  | 'python'
  | 'network'
  | 'kubernetes'
  | 'other';
export type DiagnosticSeverity = 'info' | 'warning' | 'error' | 'blocked';
/**
 * Evidence assertion semantics are deliberately closed. A declaration says
 * what a source configured, never that its target is healthy or was invoked.
 */
export type RuntimeEvidenceAssertionKind = 'observed' | 'declared';
export type RuntimeEvidenceFreshness = 'fresh' | 'stale' | 'timed_out';
/**
 * Safe, provider-specific fact families supported by the first provenance
 * slice.  New sources require an explicit enum addition rather than an
 * arbitrary source string or metadata map.
 */
export type RuntimeEvidenceKind =
  | ('docker_network_membership' | 'docker_volume_mount' | 'docker_port_publication')
  | 'docker_compose_depends_on'
  | 'docker_daemon_state_bind_mount'
  | 'systemd_requires'
  | 'systemd_wants'
  | 'systemd_part_of';
/**
 * Evidence providers are deliberately closed.  Version two adds systemd only
 * after it received its own scheduler slot; it cannot inherit a broader host
 * collection's freshness or revision.
 */
export type RuntimeEvidenceProvider = 'docker' | 'systemd';
/**
 * Fixed, schema-backed host-provider slots. This is not a plugin or policy
 * interface: the daemon owns the complete finite list.
 */
export type ProviderSlot =
  ('network_infrastructure' | 'host_scoped' | 'python_processes' | 'native_processes' | 'project_npm') | 'systemd';
export type RuntimeRelationshipKind =
  | 'connected_to'
  | 'depends_on'
  | 'required_by'
  | 'requires'
  | 'wants'
  | 'after'
  | 'before'
  | 'part_of'
  | 'binds_to'
  | 'conflicts_with'
  | 'mounts'
  | 'manages'
  | 'exposes'
  | 'exposes_daemon_state'
  | 'runs_on'
  | 'uses'
  | 'calls'
  | 'resolves_via'
  | 'proxies_to'
  | 'contains'
  | 'owns'
  | 'related_to';
export type RuntimeNodeLayer =
  'edge' | 'host' | 'service' | 'container' | 'process' | 'session' | 'package' | 'network' | 'storage' | 'advisory';
export type RuntimeLocationKind = 'host' | 'container' | 'path' | 'cluster' | 'region' | 'workspace' | 'tailnet';
export type RuntimePackageManager = 'npm' | 'pnpm' | 'yarn' | 'pip' | 'apt' | 'apk' | 'brew' | 'cargo' | 'system';
export type RuntimeOwnershipKind = 'person' | 'team' | 'system' | 'automation' | 'vendor';
export type RuntimeAdvisorySeverity = 'low' | 'moderate' | 'high' | 'critical';
export type RuntimeHealthState = 'healthy' | 'degraded' | 'unhealthy' | 'unknown';
export type RuntimeLogLevel = 'debug' | 'info' | 'warn' | 'error';
export type RuntimeServiceStatus = 'running' | 'starting' | 'stopping' | 'stopped' | 'degraded' | 'failed' | 'unknown';
export type RuntimeNodeKind =
  | 'container'
  | 'docker_network'
  | 'docker_volume'
  | 'host'
  | 'host_risk'
  | 'service'
  | 'systemd_service'
  | 'scheduled_job'
  | 'pm2_app'
  | 'tmux_session'
  | 'tailnet_node'
  | 'reverse_proxy'
  | 'local_dns_resolver'
  | 'dns_provider'
  | 'node_application'
  | 'python_application'
  | 'ai_agent'
  | 'package'
  | 'storage'
  | 'external_api'
  | 'package_dependency'
  | 'database'
  | 'worker'
  | 'process'
  | 'network_listener'
  | 'orchestrator_workload';
export type ProviderStateKind = 'fresh' | 'stale' | 'collecting' | 'unavailable' | 'timed_out' | 'disabled';
/**
 * A deliberately small, non-diagnostic explanation for a provider slot that
 * is not currently serving fresh observations.  This is a closed enum rather
 * than provider supplied text: command lines, paths, error output and other
 * host details must never cross the runtime-map boundary through this field.
 */
export type ProviderStatusReason =
  'initial' | 'refreshing' | 'collection_failed' | 'collection_timed_out' | 'source_reset' | 'disabled';
export type MountCorrelationStatus = 'matched' | 'missing' | 'extra';
export type ComposeRelationshipKind = 'declares_mount' | 'mounted_at';
export type ComposeNodeKind = 'service' | 'host_path' | 'container_path' | 'named_volume' | 'anonymous_volume';
export type LogLevel = 'info' | 'warn' | 'error';
export type HealthState = 'ok' | 'degraded';
/**
 * Closed rule identifiers keep clients from treating findings as arbitrary
 * provider messages. New rules require an explicit contract addition.
 */
export type FindingRule =
  | 'systemd.requires_target_not_active'
  | 'docker.internal_network_member_publishes_port'
  | 'docker.daemon_state_bind_mount';
/**
 * Findings are intentionally a small, closed advisory vocabulary. They do
 * not expose provider output or prescribe an automated remediation.
 */
export type FindingSeverity = 'warning' | 'advisory';
/**
 * Closed status classes prevent raw Docker status text from entering the
 * temporal-history boundary.
 */
export type ObservedContainerStatus = 'running' | 'stopped' | 'other';
/**
 * A deliberately small, daemon-lifetime observation delta. It is derived
 * from two published Docker inventories, not from Docker's event stream.
 */
export type ObservedChangeKind = 'container_appeared' | 'container_disappeared' | 'container_status_changed';

export interface DockerSnapshot {
  containers: ContainerRecord[];
  images: ImageRecord[];
  lastUpdated: number;
  /**
   * Opaque daemon-publication revision. This is a process-instance scoped,
   * monotonic cache revision, not a timestamp and not a content hash.
   */
  modelRevision: string;
  networks: NetworkRecord[];
  /**
   * ACTUAL source of these bytes: "docker" (live daemon collection) or
   * "mock" (daemon mock fallback). Stamped by the daemon route layer from
   * the cache's runtime mode so every model-bearing response attests its
   * real source (#85 A3). Optional so existing constructors compile
   * untouched; serialized only when present.
   */
  source?: RuntimeMode | null;
  volumes: VolumeRecord[];
}
export interface ContainerRecord {
  dependsOn: string[];
  id: string;
  image: string;
  mounts: ContainerMount[];
  name: string;
  networks: string[];
  ports: string[];
  role: string;
  status: string;
}
export interface ContainerMount {
  id: string;
  kind: ComposeMountKind;
  readOnly: boolean;
  source?: string | null;
  target: string;
}
export interface ImageRecord {
  containers: string[];
  image: string;
  status: string;
}
export interface NetworkRecord {
  driver: string;
  id: string;
  internal: boolean;
  members: string[];
  name: string;
}
export interface VolumeRecord {
  attachedTo: string[];
  id: string;
  name: string;
}
export interface GraphResponse {
  edges: GraphEdge[];
  nodes: GraphNode[];
}
export interface GraphEdge {
  relationship: RelationshipKind;
  source: string;
  target: string;
}
export interface GraphNode {
  id: string;
  label: string;
  type: NodeKind;
}
export interface RuntimeMap {
  diagnostics: RuntimeMapDiagnostic[];
  edges: RuntimeMapEdge[];
  lastUpdated: number;
  modelRevision: string;
  nodes: RuntimeMapNode[];
  /**
   * @minItems 6
   * @maxItems 6
   */
  providerStates: [ProviderState, ProviderState, ProviderState, ProviderState, ProviderState, ProviderState];
  /**
   * ACTUAL source of these bytes: "docker" or "mock" (#85 A3). Stamped by
   * the daemon route layer from the cache's runtime mode.
   */
  source?: RuntimeMode | null;
}
export interface RuntimeMapDiagnostic {
  message: string;
  provider: RuntimeProviderKind;
  severity: DiagnosticSeverity;
}
export interface RuntimeMapEdge {
  /**
   * Empty for relationship families that have not yet been migrated to the
   * evidence model. It remains present on the wire so API/UI consumers have
   * one stable, bounded relationship shape while the migration continues.
   *
   * @maxItems 8
   */
  evidenceRefs:
    | []
    | [RuntimeEvidenceRef]
    | [RuntimeEvidenceRef, RuntimeEvidenceRef]
    | [RuntimeEvidenceRef, RuntimeEvidenceRef, RuntimeEvidenceRef]
    | [RuntimeEvidenceRef, RuntimeEvidenceRef, RuntimeEvidenceRef, RuntimeEvidenceRef]
    | [RuntimeEvidenceRef, RuntimeEvidenceRef, RuntimeEvidenceRef, RuntimeEvidenceRef, RuntimeEvidenceRef]
    | [
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef
      ]
    | [
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef
      ]
    | [
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef,
        RuntimeEvidenceRef
      ];
  metadata: {
    [k: string]: string;
  };
  relationship: RuntimeRelationshipKind;
  source: string;
  target: string;
}
/**
 * A compact, versioned reference to the bounded fact supporting a runtime
 * relationship.  It intentionally contains no raw command output, config
 * fragment, path, process arguments, or generic metadata bag.
 */
export interface RuntimeEvidenceRef {
  assertionKind: RuntimeEvidenceAssertionKind;
  collectedAt: number;
  freshness: RuntimeEvidenceFreshness;
  id: string;
  kind: RuntimeEvidenceKind;
  provider: RuntimeEvidenceProvider;
  /**
   * Opaque provider observation token, not a cache-publication revision,
   * command output, or source dump.
   */
  providerRevision: string;
  /**
   * Version-two provider evidence is explicitly tied to the finite
   * scheduler slot that supplied its revision and freshness. Version one
   * Docker evidence intentionally has no host-provider slot.
   */
  providerSlot?: ProviderSlot | null;
  /**
   * The already-public runtime entity whose Docker fact was observed.
   */
  subjectRef: string;
  /**
   * A bounded, curated explanation; it is never copied from a raw source.
   */
  summary: string;
  /**
   * Version of this closed evidence representation, not a provider API
   * version.  It lets future additions remain explicit and reviewable.
   */
  version: number;
}
export interface RuntimeMapNode {
  id: string;
  label: string;
  layer?: RuntimeNodeLayer | null;
  metadata: {
    [k: string]: string;
  };
  package?: RuntimePackageEntity | null;
  provider: RuntimeProviderKind;
  service?: RuntimeServiceEntity | null;
  status?: string | null;
  type: RuntimeNodeKind;
}
export interface RuntimePackageEntity {
  dependencies: string[];
  dependents: string[];
  /**
   * Reserved — not emitted by current collectors.
   */
  location?: RuntimeLocation | null;
  manager: RuntimePackageManager;
  name: string;
  /**
   * Reserved — not emitted by current collectors.
   */
  owner?: RuntimeOwnership | null;
  /**
   * Reserved — not emitted by current collectors.
   */
  update?: RuntimePackageUpdate | null;
  version: string;
}
export interface RuntimeLocation {
  detail?: string | null;
  kind: RuntimeLocationKind;
  value: string;
}
export interface RuntimeOwnership {
  id?: string | null;
  kind: RuntimeOwnershipKind;
  name: string;
}
export interface RuntimePackageUpdate {
  advisories: RuntimePackageAdvisory[];
  available: boolean;
  currentVersion: string;
  latestVersion?: string | null;
}
export interface RuntimePackageAdvisory {
  fixedVersion?: string | null;
  id: string;
  publishedAt?: number | null;
  severity: RuntimeAdvisorySeverity;
  source: string;
  title: string;
  url?: string | null;
}
export interface RuntimeServiceEntity {
  dependencies: string[];
  dependents: string[];
  /**
   * Reserved — not emitted by current collectors.
   */
  events: RuntimeEventRef[];
  /**
   * Reserved — not emitted by current collectors.
   */
  health?: RuntimeHealth | null;
  /**
   * Reserved — not emitted by current collectors.
   */
  location?: RuntimeLocation | null;
  /**
   * Reserved — not emitted by current collectors.
   */
  logs: RuntimeLogRef[];
  name: string;
  /**
   * Reserved — not emitted by current collectors.
   */
  owner?: RuntimeOwnership | null;
  status: RuntimeServiceStatus;
}
export interface RuntimeEventRef {
  id: string;
  kind: string;
  message?: string | null;
  timestamp?: number | null;
}
export interface RuntimeHealth {
  checkedAt?: number | null;
  message?: string | null;
  source?: string | null;
  state: RuntimeHealthState;
}
export interface RuntimeLogRef {
  id: string;
  level?: RuntimeLogLevel | null;
  source: string;
}
export interface ProviderState {
  consecutiveFailureCount: number;
  /**
   * Opaque, per-slot data identity. It is absent before a successful pass
   * and after a source reset, and otherwise advances only for sanitized
   * observable slot-data changes.
   */
  dataRevision: string | null;
  /**
   * Wall-clock collection timestamps are nullable because a slot can have
   * no attempt yet (or its source was reset).  The upper bound preserves
   * lossless JSON transport through JavaScript's numeric representation.
   */
  lastAttemptMs: number | null;
  /**
   * Duration of the last successful collection. Failed and timed-out
   * passes deliberately retain this last known-good evidence.
   */
  lastDurationMs: number | null;
  lastSuccessMs: number | null;
  slot: ProviderSlot;
  state: ProviderStateKind;
  /**
   * Null for fresh and initial-unavailable slots. Non-null values are the
   * closed, safe transitional/exceptional reasons above, never raw errors.
   */
  statusReason: ProviderStatusReason | null;
}
export interface ComposeScan {
  correlations: MountCorrelation[];
  diagnostics: ComposeDiagnostic[];
  files: string[];
  mounts: ComposeMount[];
  projectRoot: string;
  services: ComposeService[];
}
export interface MountCorrelation {
  composeMountId?: string | null;
  container?: string | null;
  declaredSource?: string | null;
  id: string;
  kind: ComposeMountKind;
  runtimeSource?: string | null;
  service: string;
  status: MountCorrelationStatus;
  target: string;
}
export interface ComposeDiagnostic {
  id: string;
  message: string;
  origin: ComposeFileOrigin;
  severity: DiagnosticSeverity;
}
export interface ComposeFileOrigin {
  field: string;
  file: string;
  service?: string | null;
}
export interface ComposeMount {
  id: string;
  kind: ComposeMountKind;
  origin: ComposeFileOrigin;
  readOnly: boolean;
  resolvedSource?: string | null;
  service: string;
  source?: string | null;
  target: string;
}
export interface ComposeService {
  dependsOn: string[];
  environment: {
    [k: string]: string;
  };
  image?: string | null;
  name: string;
}
export interface ComposeGraph {
  edges: ComposeGraphEdge[];
  nodes: ComposeGraphNode[];
}
export interface ComposeGraphEdge {
  relationship: ComposeRelationshipKind;
  source: string;
  target: string;
}
export interface ComposeGraphNode {
  id: string;
  label: string;
  type: ComposeNodeKind;
}
export interface ComposeEditPlan {
  diagnostics: ComposeDiagnostic[];
  file: string;
  mountId: string;
  newSource?: string | null;
  newTarget?: string | null;
  originalSource?: string | null;
  originalTarget: string;
  service: string;
  unifiedDiff: string;
  willWrite: boolean;
}
export interface LogsResponse {
  entries: LogEntry[];
  nextCursor?: string | null;
  service?: string | null;
  /**
   * ACTUAL source of these bytes: "docker" or "mock" (#85 A3 / #87 E1).
   * Stamped by the daemon route layer from the cache's runtime mode so
   * fabricated mock log lines can never be shown as live host activity.
   */
  source?: RuntimeMode | null;
}
export interface LogEntry {
  container: string;
  id: string;
  level: LogLevel;
  message: string;
  timestamp: number;
}
export interface HealthResponse {
  dockerReachable: boolean;
  lastUpdated: number;
  message?: string | null;
  mode: RuntimeMode;
  modelRevision: string;
  snapshotVersion: string;
  status: HealthState;
}
export interface ContainersResponse {
  containers: ContainerRecord[];
}
export interface ImagesResponse {
  images: ImageRecord[];
}
export interface NetworksResponse {
  networks: NetworkRecord[];
}
export interface VolumesResponse {
  volumes: VolumeRecord[];
}
export interface FindingsResponse {
  findings: Finding[];
  modelRevision: string;
}
export interface Finding {
  /**
   * Canonical, already-sanitized runtime evidence that directly triggered
   * this finding. Each closed rule has a fixed, small evidence budget,
   * preventing this response from becoming a generic metadata channel.
   *
   * @minItems 1
   * @maxItems 2
   */
  evidenceRefs: [RuntimeEvidenceRef] | [RuntimeEvidenceRef, RuntimeEvidenceRef];
  id: string;
  recommendation: string;
  ruleId: FindingRule;
  severity: FindingSeverity;
  subjectRef: string;
  summary: string;
  targetRef: string;
}
/**
 * Bounded in-memory history for the daemon process only. `mock` never
 * inherits a Docker baseline or events from an earlier source generation.
 */
export interface ObservedChangeHistoryResponse {
  baselineEstablished: boolean;
  currentModelRevision: string | null;
  /**
   * @maxItems 64
   */
  events: ObservedChangeEvent[];
  observedRevision: string | null;
  source: RuntimeMode;
}
/**
 * One observed inventory delta. `containerId` is an opaque digest-derived
 * history identity, never a raw Docker ID, readable ID fragment, or name.
 */
export interface ObservedChangeEvent {
  containerId: string;
  /**
   * Schema-only union keeps optional status values required on the wire while
   * accurately admitting the null state used by appearance/disappearance.
   */
  currentStatus: ObservedContainerStatus | null;
  id: string;
  kind: ObservedChangeKind;
  observedAtMs: number;
  /**
   * Schema-only union keeps optional status values required on the wire while
   * accurately admitting the null state used by appearance/disappearance.
   */
  previousStatus: ObservedContainerStatus | null;
}

// Rust's transparent route wrapper serializes as the record itself.
export type ContainerDetailResponse = ContainerRecord;
// Stable aliases distinguish the exact daemon shapes from Node-owned API overlays.
export type DaemonRuntimeMap = RuntimeMap;
export type DaemonRuntimeMapNode = RuntimeMapNode;
export type DaemonRuntimeMapEdge = RuntimeMapEdge;
