// Generated by `npm run generate:contracts`; do not edit.
// Rust Serde/Schemars models are the declaration authority.

export type RustDaemonModels =
  | DockerSnapshot
  | GraphResponse
  | RuntimeMap
  | ComposeScan
  | ComposeGraph
  | ComposeEditPlan
  | LogsResponse
  | HealthResponse
  | ContainersResponse
  | ContainerRecord
  | ImagesResponse
  | NetworksResponse
  | VolumesResponse;
export type ComposeMountKind = 'bind' | 'named_volume' | 'anonymous_volume' | 'unsupported';
export type RuntimeMode = 'docker' | 'mock';
export type RelationshipKind = 'connected_to' | 'mounts';
export type NodeKind = 'container' | 'network' | 'volume';
export type RuntimeProviderKind =
  | 'docker'
  | 'compose'
  | 'host'
  | 'systemd'
  | 'scheduled_job'
  | 'npm'
  | 'pm2'
  | 'tmux'
  | 'tailscale'
  | 'headscale'
  | 'cloudflare'
  | 'caddy'
  | 'reverse_proxy'
  | 'local_dns'
  | 'dns_provider'
  | 'external_api'
  | 'process'
  | 'python'
  | 'network'
  | 'kubernetes'
  | 'other';
export type DiagnosticSeverity = 'info' | 'warning' | 'error' | 'blocked';
export type RuntimeRelationshipKind =
  | 'connected_to'
  | 'depends_on'
  | 'required_by'
  | 'requires'
  | 'wants'
  | 'after'
  | 'before'
  | 'part_of'
  | 'binds_to'
  | 'conflicts_with'
  | 'mounts'
  | 'manages'
  | 'exposes'
  | 'runs_on'
  | 'uses'
  | 'calls'
  | 'resolves_via'
  | 'proxies_to'
  | 'contains'
  | 'owns'
  | 'related_to';
export type RuntimeNodeLayer =
  'edge' | 'host' | 'service' | 'container' | 'process' | 'session' | 'package' | 'network' | 'storage' | 'advisory';
export type RuntimeLocationKind = 'host' | 'container' | 'path' | 'cluster' | 'region' | 'workspace' | 'tailnet';
export type RuntimePackageManager = 'npm' | 'pnpm' | 'yarn' | 'pip' | 'apt' | 'apk' | 'brew' | 'cargo' | 'system';
export type RuntimeOwnershipKind = 'person' | 'team' | 'system' | 'automation' | 'vendor';
export type RuntimeAdvisorySeverity = 'low' | 'moderate' | 'high' | 'critical';
export type RuntimeHealthState = 'healthy' | 'degraded' | 'unhealthy' | 'unknown';
export type RuntimeLogLevel = 'debug' | 'info' | 'warn' | 'error';
export type RuntimeServiceStatus = 'running' | 'starting' | 'stopping' | 'stopped' | 'degraded' | 'failed' | 'unknown';
export type RuntimeNodeKind =
  | 'container'
  | 'docker_network'
  | 'docker_volume'
  | 'host'
  | 'service'
  | 'systemd_service'
  | 'scheduled_job'
  | 'pm2_app'
  | 'tmux_session'
  | 'tailnet_node'
  | 'reverse_proxy'
  | 'local_dns_resolver'
  | 'dns_provider'
  | 'node_application'
  | 'python_application'
  | 'ai_agent'
  | 'package'
  | 'storage'
  | 'external_api'
  | 'package_dependency'
  | 'database'
  | 'worker'
  | 'process'
  | 'network_listener'
  | 'orchestrator_workload';
export type MountCorrelationStatus = 'matched' | 'missing' | 'extra';
export type ComposeRelationshipKind = 'declares_mount' | 'mounted_at';
export type ComposeNodeKind = 'service' | 'host_path' | 'container_path' | 'named_volume' | 'anonymous_volume';
export type LogLevel = 'info' | 'warn' | 'error';
export type HealthState = 'ok' | 'degraded';

export interface DockerSnapshot {
  containers: ContainerRecord[];
  images: ImageRecord[];
  lastUpdated: number;
  networks: NetworkRecord[];
  /**
   * ACTUAL source of these bytes: "docker" (live daemon collection) or
   * "mock" (daemon mock fallback). Stamped by the daemon route layer from
   * the cache's runtime mode so every model-bearing response attests its
   * real source (#85 A3). Optional so existing constructors compile
   * untouched; serialized only when present.
   */
  source?: RuntimeMode | null;
  volumes: VolumeRecord[];
}
export interface ContainerRecord {
  dependsOn: string[];
  id: string;
  image: string;
  mounts: ContainerMount[];
  name: string;
  networks: string[];
  ports: string[];
  role: string;
  status: string;
}
export interface ContainerMount {
  id: string;
  kind: ComposeMountKind;
  readOnly: boolean;
  source?: string | null;
  target: string;
}
export interface ImageRecord {
  containers: string[];
  image: string;
  status: string;
}
export interface NetworkRecord {
  driver: string;
  id: string;
  internal: boolean;
  members: string[];
  name: string;
}
export interface VolumeRecord {
  attachedTo: string[];
  id: string;
  name: string;
}
export interface GraphResponse {
  edges: GraphEdge[];
  nodes: GraphNode[];
}
export interface GraphEdge {
  relationship: RelationshipKind;
  source: string;
  target: string;
}
export interface GraphNode {
  id: string;
  label: string;
  type: NodeKind;
}
export interface RuntimeMap {
  diagnostics: RuntimeMapDiagnostic[];
  edges: RuntimeMapEdge[];
  lastUpdated: number;
  nodes: RuntimeMapNode[];
  /**
   * ACTUAL source of these bytes: "docker" or "mock" (#85 A3). Stamped by
   * the daemon route layer from the cache's runtime mode.
   */
  source?: RuntimeMode | null;
}
export interface RuntimeMapDiagnostic {
  message: string;
  provider: RuntimeProviderKind;
  severity: DiagnosticSeverity;
}
export interface RuntimeMapEdge {
  metadata: {
    [k: string]: string;
  };
  relationship: RuntimeRelationshipKind;
  source: string;
  target: string;
}
export interface RuntimeMapNode {
  id: string;
  label: string;
  layer?: RuntimeNodeLayer | null;
  metadata: {
    [k: string]: string;
  };
  package?: RuntimePackageEntity | null;
  provider: RuntimeProviderKind;
  service?: RuntimeServiceEntity | null;
  status?: string | null;
  type: RuntimeNodeKind;
}
export interface RuntimePackageEntity {
  dependencies: string[];
  dependents: string[];
  /**
   * Reserved — not emitted by current collectors.
   */
  location?: RuntimeLocation | null;
  manager: RuntimePackageManager;
  name: string;
  /**
   * Reserved — not emitted by current collectors.
   */
  owner?: RuntimeOwnership | null;
  /**
   * Reserved — not emitted by current collectors.
   */
  update?: RuntimePackageUpdate | null;
  version: string;
}
export interface RuntimeLocation {
  detail?: string | null;
  kind: RuntimeLocationKind;
  value: string;
}
export interface RuntimeOwnership {
  id?: string | null;
  kind: RuntimeOwnershipKind;
  name: string;
}
export interface RuntimePackageUpdate {
  advisories: RuntimePackageAdvisory[];
  available: boolean;
  currentVersion: string;
  latestVersion?: string | null;
}
export interface RuntimePackageAdvisory {
  fixedVersion?: string | null;
  id: string;
  publishedAt?: number | null;
  severity: RuntimeAdvisorySeverity;
  source: string;
  title: string;
  url?: string | null;
}
export interface RuntimeServiceEntity {
  dependencies: string[];
  dependents: string[];
  /**
   * Reserved — not emitted by current collectors.
   */
  events: RuntimeEventRef[];
  /**
   * Reserved — not emitted by current collectors.
   */
  health?: RuntimeHealth | null;
  /**
   * Reserved — not emitted by current collectors.
   */
  location?: RuntimeLocation | null;
  /**
   * Reserved — not emitted by current collectors.
   */
  logs: RuntimeLogRef[];
  name: string;
  /**
   * Reserved — not emitted by current collectors.
   */
  owner?: RuntimeOwnership | null;
  status: RuntimeServiceStatus;
}
export interface RuntimeEventRef {
  id: string;
  kind: string;
  message?: string | null;
  timestamp?: number | null;
}
export interface RuntimeHealth {
  checkedAt?: number | null;
  message?: string | null;
  source?: string | null;
  state: RuntimeHealthState;
}
export interface RuntimeLogRef {
  id: string;
  level?: RuntimeLogLevel | null;
  source: string;
}
export interface ComposeScan {
  correlations: MountCorrelation[];
  diagnostics: ComposeDiagnostic[];
  files: string[];
  mounts: ComposeMount[];
  projectRoot: string;
  services: ComposeService[];
}
export interface MountCorrelation {
  composeMountId?: string | null;
  container?: string | null;
  declaredSource?: string | null;
  id: string;
  kind: ComposeMountKind;
  runtimeSource?: string | null;
  service: string;
  status: MountCorrelationStatus;
  target: string;
}
export interface ComposeDiagnostic {
  id: string;
  message: string;
  origin: ComposeFileOrigin;
  severity: DiagnosticSeverity;
}
export interface ComposeFileOrigin {
  field: string;
  file: string;
  service?: string | null;
}
export interface ComposeMount {
  id: string;
  kind: ComposeMountKind;
  origin: ComposeFileOrigin;
  readOnly: boolean;
  resolvedSource?: string | null;
  service: string;
  source?: string | null;
  target: string;
}
export interface ComposeService {
  dependsOn: string[];
  environment: {
    [k: string]: string;
  };
  image?: string | null;
  name: string;
}
export interface ComposeGraph {
  edges: ComposeGraphEdge[];
  nodes: ComposeGraphNode[];
}
export interface ComposeGraphEdge {
  relationship: ComposeRelationshipKind;
  source: string;
  target: string;
}
export interface ComposeGraphNode {
  id: string;
  label: string;
  type: ComposeNodeKind;
}
export interface ComposeEditPlan {
  diagnostics: ComposeDiagnostic[];
  file: string;
  mountId: string;
  newSource?: string | null;
  newTarget?: string | null;
  originalSource?: string | null;
  originalTarget: string;
  service: string;
  unifiedDiff: string;
  willWrite: boolean;
}
export interface LogsResponse {
  entries: LogEntry[];
  nextCursor?: string | null;
  service?: string | null;
  /**
   * ACTUAL source of these bytes: "docker" or "mock" (#85 A3 / #87 E1).
   * Stamped by the daemon route layer from the cache's runtime mode so
   * fabricated mock log lines can never be shown as live host activity.
   */
  source?: RuntimeMode | null;
}
export interface LogEntry {
  container: string;
  id: string;
  level: LogLevel;
  message: string;
  timestamp: number;
}
export interface HealthResponse {
  dockerReachable: boolean;
  lastUpdated: number;
  message?: string | null;
  mode: RuntimeMode;
  snapshotVersion: string;
  status: HealthState;
}
export interface ContainersResponse {
  containers: ContainerRecord[];
}
export interface ImagesResponse {
  images: ImageRecord[];
}
export interface NetworksResponse {
  networks: NetworkRecord[];
}
export interface VolumesResponse {
  volumes: VolumeRecord[];
}

// Rust's transparent route wrapper serializes as the record itself.
export type ContainerDetailResponse = ContainerRecord;
// Stable aliases distinguish the exact daemon shapes from Node-owned API overlays.
export type DaemonRuntimeMap = RuntimeMap;
export type DaemonRuntimeMapNode = RuntimeMapNode;
export type DaemonRuntimeMapEdge = RuntimeMapEdge;
